version: '3'
services:
    app: &php
        container_name: app
        image: adrianabo/php:7.4.14-fpm-pcov
        restart: on-failure
        user: www-data
        working_dir: /var/www
        volumes:
            - ./:/var/www:delegated
            - ./docker/php.ini:/usr/local/etc/php/conf.d/docker-php.ini:ro
            - composertmp:/tmp
        environment:
            - "DB_HOST=db"
            - "REDIS_HOST=redis"
            - "REDIS_PORT=6379"
            - "DB_PORT=3306"
            - "DB_DATABASE=defichain_api"
            - "DB_USERNAME=defichain_api"
            - "DB_PASSWORD=secret"
            - "COMPOSER_HOME=/tmp"
        depends_on:
            - db
            - redis

    #  worker-default:
    #    <<: *php
    #    container_name: mn_alarm_worker_default
    #    command: php artisan horizon

    docker-host:
        image: qoomon/docker-host
        cap_add: [ 'NET_ADMIN' ]
        restart: on-failure
        environment:
            - PORTS=8555

    web:
        container_name: defichain_api_web
        image: nginx:1.13-alpine
        working_dir: /var/www/html
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html:delegated
            - ./storage/app/public:/var/www/html/public/storage:delegated
        depends_on:
            - app
            - docker-host

    db:
        container_name: defichain_api_db
        image: mariadb:10.4
        restart: always
        ports:
            - "33066:3306"
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            - "MYSQL_DATABASE=defichain_api"
            - "MYSQL_USER=defichain_api"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_ROOT_PASSWORD=secret"

    redis:
        container_name: defichain_api_redis
        image: redis:3.2-alpine
        restart: always
        ports:
            - 36379:6379
        volumes:
            - redisdata:/data

volumes:
    dbdata:
    redisdata:
    composertmp:
